version: '3'
services:

  web_api:
    image: web_api
    container_name: web_api_app
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    depends_on:
      - sql
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433" 
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password123!
    volumes:
        - sql_data:/var/opt/mssql
    networks:
      - backend
networks:
  backend:
  
volumes:
  sql_data:
    driver: local
